<?php

/*
 * Editor server script for DB table user
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "extensions/Editor-1.3.3/php/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'users', 'UserId' )
	->fields(
		Field::inst( 'users.UserId' )
			->set(false),
		Field::inst( 'users.PersonNameID' )
			->set(false),
		Field::inst( 'driver_daily_availability.YN' ),
		Field::inst( 'driver_availability.StartTime' ),
		Field::inst( 'driver_availability.EndTime' ),
		Field::inst( 'person_name.FirstName' ),
		Field::inst( 'person_name.LastName' ),
		Field::inst( 'driver_availability.DayOfWeek' ),
		Field::inst( 'driver_settings.ContactPreference' ),
		Field::inst( 'driver_settings.HoursPerTime' ),
		Field::inst( 'driver_settings.HoursTimeUnit' ),
		Field::inst( 'driver_settings.DaysPerTime' ),
		Field::inst( 'driver_settings.DaysTimeUnit' ),
		Field::inst( 'driver_settings.ServiceDog' ),
		Field::inst( 'driver_settings.OtherNotes' )
	)
	->leftJoin( 'driver_daily_availability', 'driver_daily_availability.UserId', '=', 'users.UserId' )
	->leftJoin( 'person_name', 'person_name.PersonNameID', '=', 'users.PersonNameID' )
	->leftJoin( 'driver_availability', 'driver_availability.UserId','=','users.UserId' )
	->leftJoin( 'driver','driver.UserID','=','users.UserId')
	->leftJoin( 'driver_settings','driver_settings.UserID','=','users.UserId' )
	->join(
		Join::inst('phone','array')
			->join(
				array('UserId','UserID'),
				array('PhoneID','PhoneID'),
				'user_phone'
				)
			->fields(
				Field::inst( 'PhoneNumber' ),
				Field::inst( 'PhoneType' )
			)
	)
	->where( 'driver.DriverStatus',"Active",'=' )
	->where( 'users.Status','ACTIVE','=' )

	->process( $_POST )
	->json();

